# Generated by Django 4.1.3 on 2022-11-27 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
    ]
